CREATE DATABASE form;
USE form;

CREATE TABLE info (
ID INT AUTO_INCREMENT PRIMARY KEY,
Username VARCHAR(100),
Email VARCHAR(50),
Phn_Number VARCHAR(15),
Password VARCHAR (50)
);

ALTER TABLE info AUTO_INCREMENT = 1;

DELETE FROM info
WHERE ID = ID > 0;

SELECT * FROM info;