CREATE DATABASE form;
USE form;

CREATE TABLE info (
ID INT AUTO_INCREMENT PRIMARY KEY,
Username VARCHAR(100),
Email VARCHAR(50),
Phn_Number VARCHAR(15),
Password VARCHAR (50)
);

SELECT * FROM info;
